env: prod

logger:
  env: prod  # prod или dev отвечает за уровень логирования

db:
  dsn: "postgres://postgres:@127.0.0.1:5432/burovichok?sslmode=disable"
  confmigration_path: "migrations"
  max_open_conns:    1
  max_Idle_conns:    1
  conn_max_lifetime: 10
  max_retries:       10

ui:
  name: "burovichok"
  width: 1200
  height: 800
  icon_path: "assets/icon.png"
